### ISSUE TITLE
ugly error msg when hitting "cancel" in wallet upon connecting

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/hopr-admin#352]
When I connect my wallet on the Hub landing page for the very first time and then click "cancel" in my wallet (testing with MM), I get a fairly ugly huge error popup which is not meaningful to the user:
```
{"details":"User rejected the request.","shortMessage":"User rejected the request.","name":"UserRejectedRequestError","version":"viem@1.2.12","message":"User rejected the request.\n\nDetails: User rejected the request.\nVersion: viem@1.2.12","cause":{"code":4001,"message":"User rejected the request.","stack":"{\n \"code\": 4001,\n \"message\": \"User rejected the request.\",\n \"stack\": \"Error: User rejected the request.\\n at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:42930)\\n at new r.EthereumProviderError (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:43445)\\n at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:48321)\\n at Object.userRejectedRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:49552)\\n at n.userRejectedRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:278957)\\n at _.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:274083)\\n at Generator.next (<anonymous>)\\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:259065\\n at new Promise (<anonymous>)\\n at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:258810)\\n at _.rejectPermissionsRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:273908)\\n at Object.rejectPermissionsRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:1:279603)\\n at s.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:1:186275)\\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:7:38460\\n at s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:7:38530)\\n at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:79889)\\n at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:79704)\\n at y.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:80518)\\n at e.exports._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:26:326595)\\n at y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:93957)\\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:97141\\n at b.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:97168)\\n at t.exports.m (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:85089)\\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:7:38460\\n at s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:7:38530)\\n at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:79889)\\n at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:79704)\\n at y.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:80518)\\n at t.exports._onMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:295619)\\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:295466\"\n}\n at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:42930)\n at new r.EthereumProviderError (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:43445)\n at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:48321)\n at Object.userRejectedRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:49552)\n at n.userRejectedRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:278957)\n at _.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:274083)\n at Generator.next (<anonymous>)\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:259065\n at new Promise (<anonymous>)\n at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:258810)\n at _.rejectPermissionsRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:273908)\n at Object.rejectPermissionsRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:1:279603)\n at s.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:1:186275)\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:7:38460\n at s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:7:38530)\n at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:79889)\n at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:79704)\n at y.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:80518)\n at e.exports._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:26:326595)\n at y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:93957)\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:97141\n at b.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:97168)\n at t.exports.m (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:85089)\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:7:38460\n at s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:7:38530)\n at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:79889)\n at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:79704)\n at y.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:80518)\n at t.exports._onMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:295619)\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:295466"},"code":4001}
```

I suggest to present a meaningful message to the user such as `wallet has rejected the connection`.

**Comment by mjadach-iv** [comment]
Fixed
